# Generated by Django 3.0.5 on 2020-04-28 15:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('secondname', models.CharField(max_length=100, verbose_name='Отчество')),
                ('expirience', models.IntegerField(verbose_name='Опыт работы')),
            ],
            options={
                'verbose_name': 'Специалист',
                'verbose_name_plural': 'Специалисты',
            },
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RC', 'Запись подтверждена'), ('SC', 'Обследование проведено'), ('ED', 'Обследование сорвано')], default='RC', max_length=50)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата записи')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время записи')),
                ('email', models.EmailField(max_length=254, verbose_name='Email клиента')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Specialists', verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
